"use client";

import { Inter } from "next/font/google";
import "./globals.css";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "EBHTPN1",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();

  const linkClass =
    "hover:translate-x-1 hover:rounded-tl-2xl hover:rounded-bl-2xl text-black hover:text-black hover:bg-white duration-200 poppins-medium px-5 py-3 text-md";

  return (
    <html data-theme="corporate" lang="en">
      <body>
        <div className="flex-col w-full bg-11">
          <div className="">{children}</div>
        </div>
      </body>
    </html>
  );
}
